In [2]:
import numpy as np
import pandas as pd

In [3]:
pd.__version__

'2.2.3'

### Creating Series

In [6]:
data=pd.Series([1,0.45,3.6,9])
print(data)
type(data)

0    1.00
1    0.45
2    3.60
3    9.00
dtype: float64

pandas.core.series.Series

In [7]:
print(f"The vales are {data.values} and the indexes are: {data.index}")

The vales are [1.   0.45 3.6  9.  ] and the indexes are: RangeIndex(start=0, stop=4, step=1)

In [8]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

### Series from Dictionary

In [9]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [12]:
print(f"The vales are {population.values} and the indexes are: {population.index}")

The vales are [38332521 26448193 19651127 19552860 12882135] and the indexes are: Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [14]:
population['California':'Texas']

California    38332521
Texas         26448193
dtype: int64

In [11]:
population['Florida']

np.int64(19552860)

### To create a series from scalar value, an index must be provided. The scalar value will be repeated as per the length of index

In [21]:
# data can be a scalar, which is repeated to fill the specified index:
scalar=pd.Series(5, index=[100, 200, 300,400,500])
print(scalar)
print(scalar*2)
print(scalar+scalar*2)

100    5
200    5
300    5
400    5
500    5
dtype: int64
100    10
200    10
300    10
400    10
500    10
dtype: int64
100    15
200    15
300    15
400    15
500    15
dtype: int64

In [16]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area=pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

### Series from NUMPY Array

In [17]:
arr=np.array(['a','b','c','d'])
series=pd.Series(arr,index=['first','second','third','fourth'])
print(series)
type(series)

first     a
second    b
third     c
fourth    d
dtype: object

pandas.core.series.Series

In [25]:
s1=pd.Series([1,2,3,4],index=['a','b','c','d'])
s2=pd.Series([2,4,6,8,10],index=['a','b','c','d','e'])
#While adding two series, if Non-Matching Index is found in either of the Series, Then NaN will be printed corresponds to Non-Matching Index. 
print(s1+s2)
#If Non-Matching Index is found in either of the series, then this Non-Matching Index corresponding value of that series will be filled as 0.
print(s1.add(s2,fill_value=0))

a     3.0
b     6.0
c     9.0
d    12.0
e     NaN
dtype: float64
a     3.0
b     6.0
c     9.0
d    12.0
e    10.0
dtype: float64

### Selection in Series (loc , iloc and [] )

In [29]:
arr2=np.array([1,2,3,4,5,6,7,8,9])
ser=pd.Series(arr2)
print(ser)
print(ser.loc[:2])
print(ser.loc[3:4])

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
0    1
1    2
2    3
dtype: int64
3    4
4    5
dtype: int64

In [33]:
print(ser.iloc[:2])
print(ser.iloc[3:4])
print(ser.iloc[7:])

0    1
1    2
dtype: int64
3    4
dtype: int64
7    8
8    9
dtype: int64

In [38]:
print(ser[:2])
print(ser[3:4])
print(ser[7:])
print(ser[0])
print(ser.index)

0    1
1    2
dtype: int64
3    4
dtype: int64
7    8
8    9
dtype: int64
1
RangeIndex(start=0, stop=9, step=1)

### Slicing in series

In [42]:
print(ser[0:7:2])

0    1
2    3
4    5
6    7
dtype: int64

## Constructing DataFrame objects
**A Pandas DataFrame can be constructed in a variety of ways. Here we’ll give several
examples**

## From a dictionary of Series objects.

In [43]:
states=pd.DataFrame({'Population':population,'Area':area})
states

            Population    Area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [45]:
print(states.index)
print(states.columns)
print(type(states))

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
Index(['Population', 'Area'], dtype='object')
<class 'pandas.core.frame.DataFrame'>

In [46]:
states['Area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: Area, dtype: int64

## From a list of dicts

In [47]:
# Even if some keys in the dictionary are missing, Pandas will fill them in with NaN (i.e., “not a number”) values
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}],index=['A','B'])

     a  b    c
A  1.0  2  NaN
B  NaN  3  4.0

## From a two-dimensional NumPy array.

In [48]:
pd.DataFrame(np.random.rand(3, 2),
columns=['foo', 'bar'],
index=['a', 'b', 'c'])

        foo       bar
a  0.412198  0.857626
b  0.225598  0.937555
c  0.228770  0.171278

## The Pandas Index Object (Immutable)

In [49]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [50]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64

# Data Selection in Series

## Series as one-dimensional array

In [ ]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
index=['a', 'b', 'c', 'd'])
data['e'] = 1.25
data

In [ ]:
#slicing by explicit index
print(data['a':'c'])
#slicing by implicit index
print(data[0:2])
#masking
print(data[(data>0.3) & (data<0.8)])
#fancy indexing
print(data[['a','e']])

## Indexers: loc, iloc, and ix

In [ ]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
print(data)
# explicit index when indexing
print(data[1])
# implicit index when indexing
print(data[1:3])

**Loc(Explicit Index)**

In [ ]:
#loc attribute always refrence to the explicit index
print(data.loc[1])
print(data.loc[1:3])

**iLoc(Implicit Index)**

In [ ]:
#loc attribute always refrence to the implicit index
print(data.iloc[1])
print(data.iloc[1:3])

# Data Selection in DataFrame

**DataFrame as a dictionary**

In [ ]:
area = pd.Series({'California': 423967, 'Texas': 695662,'New York': 141297, 'Florida': 170312,'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,'New York': 19651127, 'Florida': 19552860,'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

In [ ]:
#acceessing via dictionary style indexing
print(data['area'])
print(data.area)

In [ ]:
data['density']=data['pop']/data['area']
data

**DataFrame as two-dimensional array**

In [ ]:
data.values

In [ ]:
#Transpose
data.T

In [ ]:
print(data.values[0])
print(data['area'])

**Implicit Indexing**

In [ ]:
print(data)
print(data.iloc[:3,1:3])

**Explicit Indexing**

In [ ]:
print(data.loc[:'Illinois', :'pop'])

**Loc with masking and fency indexing**

In [ ]:
data.loc[data.density>100,['pop','density']]

In [ ]:
#modification of values
data.iloc[0, 2] = 90
data

In [ ]:
#indexing refers to columns, slicing refers to rows:
print(data['Florida':'Illinois'])
print(data[1:3])
print(data[data.density > 100])

## Methods of MultiIndex Creation

In [ ]:
df = pd.DataFrame(np.random.rand(4, 2),
index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
columns=['data1', 'data2'])
df

In [ ]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 1937810}
pd.Series(data)

In [ ]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

In [ ]:
pop['California']

## Simple Concatenation with pd.concat

In [ ]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])

In [ ]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
# pd.concat([df1,df2])
print(df1); print(df2)

## Specifying Set Arithmetic for Joins

In [ ]:
df1 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                    columns=['name', 'food'])
df2 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                    columns=['name', 'drink'])
print(pd.merge(df1,df2))
# intersection of the two sets of inputs
#pd.merge(df6, df7, how='inner')

   name   food drink
0  Mary  bread  wine

In [4]:
#union of the input columns
print(pd.merge(df1, df2, how='outer'))

     name   food drink
0  Joseph    NaN  beer
1    Mary  bread  wine
2    Paul  beans   NaN
3   Peter   fish   NaN

## Example: US States Data

In [5]:
pop = pd.read_csv('state-population.csv')
areas = pd.read_csv('state-areas.csv')
abbrevs = pd.read_csv('state-abbrevs.csv')

In [7]:
print(pop.head())
print(areas.head())
print(abbrevs.head())

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0
        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707
        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [9]:
merged = pd.merge(pop, abbrevs, how='outer',
                  left_on='state/region', right_on='abbreviation')
merged

     state/region     ages  year  population    state abbreviation
0              AK    total  1990    553290.0   Alaska           AK
1              AK  under18  1990    177502.0   Alaska           AK
2              AK    total  1992    588736.0   Alaska           AK
3              AK  under18  1991    182180.0   Alaska           AK
4              AK  under18  1992    184878.0   Alaska           AK
...           ...      ...   ...         ...      ...          ...
2539           WY  under18  1993    137458.0  Wyoming           WY
2540           WY    total  1991    459260.0  Wyoming           WY
2541           WY  under18  1991    136720.0  Wyoming           WY
2542           WY  under18  1990    136078.0  Wyoming           WY
2543           WY    total  1990    453690.0  Wyoming           WY

[2544 rows x 6 columns]

In [14]:
merged = merged.drop('abbreviation', axis=1)
merged

     state/region     ages  year  population    state
0              AK    total  1990    553290.0   Alaska
1              AK  under18  1990    177502.0   Alaska
2              AK    total  1992    588736.0   Alaska
3              AK  under18  1991    182180.0   Alaska
4              AK  under18  1992    184878.0   Alaska
...           ...      ...   ...         ...      ...
2539           WY  under18  1993    137458.0  Wyoming
2540           WY    total  1991    459260.0  Wyoming
2541           WY  under18  1991    136720.0  Wyoming
2542           WY  under18  1990    136078.0  Wyoming
2543           WY    total  1990    453690.0  Wyoming

[2544 rows x 5 columns]

In [17]:
merged[merged['population'].isnull()]

     state/region     ages  year  population state
1872           PR  under18  1990         NaN   NaN
1873           PR    total  1990         NaN   NaN
1874           PR    total  1991         NaN   NaN
1875           PR  under18  1991         NaN   NaN
1876           PR    total  1993         NaN   NaN
1877           PR  under18  1993         NaN   NaN
1878           PR  under18  1992         NaN   NaN
1879           PR    total  1992         NaN   NaN
1880           PR  under18  1994         NaN   NaN
1881           PR    total  1994         NaN   NaN
1882           PR    total  1995         NaN   NaN
1883           PR  under18  1995         NaN   NaN
1884           PR  under18  1996         NaN   NaN
1885           PR    total  1996         NaN   NaN
1886           PR  under18  1998         NaN   NaN
1887           PR    total  1998         NaN   NaN
1888           PR    total  1997         NaN   NaN
1889           PR  under18  1997         NaN   NaN
1890           PR    total  1999         NaN   NaN
1891           PR  under18  1999         NaN   NaN

In [18]:
merged.loc[merged['state/region'] == 'PR', 'state'] = 'Puerto Rico'
merged.loc[merged['state/region'] == 'USA', 'state'] = 'United States'
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state           False
dtype: bool